import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/commons/Header";
import { AppProvider } from "./context/AppContext";
import "./globals.css";
import Footer from "./components/commons/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next"
const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LDT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <AppProvider>
      <html lang="en">
        <body
          className={`${interSans.className} antialiased`}
        >
          <Header />
          <main className="main-wrapper">
            {children}
          </main>
          <SpeedInsights />
          <Footer />
        </body>
      </html>
    </AppProvider>
  );
}
