import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/commons/Header";
import MainWrapper from "./components/commons/MainWrapper";
import "./globals.css";
import { AppProvider } from "./context/AppContext";

const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <AppProvider>
      <html lang="en">
        <body
          className={`${interSans.className} antialiased`}
        >
          <Header />
          <MainWrapper>
            {children}
          </MainWrapper>
        </body>
      </html>
    </AppProvider>
  );
}
