import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '../components/commons/Footer';
import Header from '../components/commons/Header';
import { AppProvider } from '../context/AppContext';
import '../globals.css';

const interSans = Inter({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'LDT',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: { lang: string };
}>) {
    return (
        <AppProvider>
            <html lang={params.lang}>
                <body
                    className={`${interSans.className} antialiased`}
                >
                    <Header />
                    <main className="main-wrapper">
                        {children}
                    </main>
                    <SpeedInsights />
                    <Footer />
                </body>
            </html>
        </AppProvider>
    );
}
